name: pocketflow
description: A minimalist LLM framework, ported from Python to Dart.
version: 0.1.0


environment:
  sdk: ^3.9.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
